name: ci
on:
  push: { branches: ["main", "feature/**"] }
  pull_request: {}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Apply Supabase schema
        run: supabase db push --db-url "$DATABASE_URL"
      # TODO: Fix ESLint circular structure issue with Next.js 15.5 + ESLint 9
      # - run: pnpm lint
      - name: Print Environment Variables for Debugging
        run: env | sort
      - run: pnpm build
      - run: pnpm test
    env:
      NEXT_TELEMETRY_DISABLED: 1
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
